- .changeset/nice-bottles-unite.md
- CHANGELOG.md
- deployments/avs/README.md
- deployments/avs/ethereum.yaml
- deployments/avs/holesky.yaml
- package.json
ProxyAdmin with owner: 0xfaD1C94469700833717Fa8a3017278BC1cA8031C
Yes
Have any new metadata configs and deployment addresses been used with any Hyperlane tooling, such as the CLI?
No
> feat: add holesky addresses

- .changeset/clean-carrots-report.md
- .changeset/shaggy-chicken-hunt.md
- chains/arbitrum/metadata.yaml
- chains/mantapacific/metadata.yaml
Added the gnosisSafeTransactionServiceUrl
Added more RPC URLs for arbitrum, the one before was unusable with very frequent RPCs being made. E.g. when using the CLI's `ism read`, a bunch of these ultimately resulting in a throw:
```
Slow response from provider #0.
Slow response from provider #0.
All providers timed out for method call
All providers timed out for method call
```
> Add mantapacific gnosisSafeTransactionServiceUrl

- .changeset/real-peaches-sneeze.md
- deployments/warp_routes/ECLIP/arbitrum-neutron-config.yaml
- deployments/warp_routes/TIA/arbitrum-neutron-config.yaml
- deployments/warp_routes/TIA/manta-neutron-config.yaml
Add missing neutron token definitions to warp configs. Required for use with WarpCore which will look for these tokens when they're used for IGP fees.
Yes
Tested in UI
> Add missing neutron token definitions to warp configs

- chains/scroll/metadata.yaml
update scroll safe url, taken from https://docs.safe.global/core-api/transaction-service-supported-networks
> chore: update `gnosisSafeTransactionServiceUrl` for scroll

- .changeset/kind-olives-change.md
- src/utils.ts
fixes #84 
Yes
It's only sorting in YAML strings generated.
I've tested with success the unit test below by just adding the logging of the metadata added from mock:
```
yarn mocha --config .mocharc.json './test/unit/registry.test.ts' -f 'Adds a new chain' --exit
Registry utilities
Chain mockchain not found in registry, adding it now
Added chain {
blockExplorers: [
{
apiUrl: 'https://api.etherscan.io/api',
family: 'etherscan',
name: 'Etherscan',
url: 'https://etherscan.io'
},
{
apiUrl: 'https://eth.blockscout.com/api',
family: 'blockscout',
name: 'Blockscout',
url: 'https://blockscout.com/eth/mainnet'
}
],
blocks: { confirmations: 7, estimateBlockTime: 13, reorgPeriod: 14 },
chainId: 1,
displayName: 'Ethereum',
domainId: 1,
gnosisSafeTransactionServiceUrl: …
```
> fix: sort entries in YAML as required by CI

- test/unit/registry.test.ts
Now that #78 is merged, the test branch can be set back to main
> Change registry test branch back to main

- .github/workflows/combine.yml
- chains/metadata.yaml
An issue I didn't consider: PRs from 3rd parties don't have the secret token required for the combine job to commit. Running the update manually and adding a fallback to the default github secret token, which has the downside of not re-triggering CIs but should still be able to commit if their repo settings allow it.
> Update combined data

- .changeset/large-pans-obey.md
- chains/metadata.yaml
- chains/redstone/metadata.yaml
- Fix redstone gnosisSafeTransactionServiceUrl
> fix: Set correct redstone gnosisSafeTransactionServiceUrl in metadata

- .github/workflows/ci.yml
**problem**
the changeset release PRs get errors saying "Some packages have been changed but no changesets were found", because part of the process is moving the changeset contents to the readme and cleaning up all changesets. This is now a problem because the CI check expects there to be a changeset.
- fix: changeset ci check is no-op on release PRs
> fix: changeset ci check is no-op on release PRs

- .github/workflows/ci.yml
- fix: check changeset only on non-release PRs
- will be skipped if branch is `changeset-release/main` or running in the merge queue
> fix: check changeset only on non-release PRs

- .changeset/great-crews-draw.md
- .changeset/tough-parrots-suffer.md
- chains/metadata.yaml
- chains/sepolia/metadata.yaml
- chains/zetachain/metadata.yaml
- This "athens" zetachain rpcUrl is actually a testnet URL - oops! Replaced with another URL from https://www.zetachain.com/docs/reference/network/api/#public-endpoints. This should fix some scripts that were falling back to this URL
- Added the Sepolia Safe transaction service URL - I used this for some testing recently
> fix: replace incorrect zetachain rpcUrl, add sepolia Safe transaction service URL

- .changeset/three-socks-prove.md
- deployments/warp_routes/TIA/mantapacific-neutron-config.yaml
- Fix TIA-mantapacific-neutron warp config by removing reference to the Tia arbitrum neutron HypCollateral router
> fix(deployments): Fix TIA-mantapacific-neutron warp config

- .changeset/brave-gorillas-refuse.md
- chains/metadata.yaml
- chains/polygon/metadata.yaml
- Makes it 3, matching what we use internally in infra deployments https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/infra/config/environments/mainnet3/chains.ts#L23
- A response to https://discord.com/channels/935678348330434570/961710804011458621/1276321809872191572
- waiting 200 blocks for each transaction is unreasonable and results in timeouts in the CLI
> chore: lower the polygon confirmations

- .changeset/witty-zoos-doubt.md
- chains/metadata.yaml
- chains/neutron/metadata.yaml
As Cosmos indexing requires an archive node, adding a public one
> feat: add an archive RPC node for Neutron

- .changeset/hot-flies-speak.md
- chains/pulsechain/metadata.yaml
This PR adds the additional configurations for PulseChain to the Hyperlane registry. 
The changes include:
**Block explorers:** 
- Explorer 1
apiUrl: https://api.scan.pulsechain.com/api
family: blockscout
name: Pulsechain Explorer
url: https://oldscan.gopulse.com/#/
- Explorer 2
apiUrl: https://api.scan.pulsechain.com/api
family: other
name: Otterscan
url: https://otter.pulsechain.com
**Increased estimateBlockTime**
estimateBlockTime: 10
**Additional RPC URL:** 
https://pulsechain-rpc.publicnode.com
Yes
Yes
I have tested the PulseChain configurations locally and successfully deployed the core contracts to PulseChain with the configurations I have updated. But, while trying to deploy the contracts with the chain configurations in the registry, the transaction is not going through, and …
> Update pulsechain metadata

- .changeset/smooth-ducks-wave.md
- deployments/warp_routes/SOL/eclipsemainnet-solanamainnet-addresses.yaml
- deployments/warp_routes/SOL/eclipsemainnet-solanamainnet-config.yaml
> fix: update warp route addresses

- .changeset/breezy-poets-suffer.md
- deployments/warp_routes/USDC/ethereum-eclipsemainnet-solanamainnet-addresses.yaml
- deployments/warp_routes/USDC/ethereum-eclipsemainnet-solanamainnet-config.yaml
- update USDC solana, ethereum, eclipse warp config
> fix(warp): Update solana eclipse USDC warp route addresses

- .changeset/sweet-dolls-know.md
- deployments/warp_routes/tETH/ethereum-eclipsemainnet-addresses.yaml
- deployments/warp_routes/tETH/ethereum-eclipsemainnet-config.yaml
- Update ethereum / eclipse tETH warp config and addresses
> fix(warp): Update ethereum / eclipse tETH warp config and addresses

- .changeset/two-boxes-compete.md
- chains/camptestnet/metadata.yaml
- chains/formtestnet/metadata.yaml
- chains/metadata.yaml
- chains/soneiumtestnet/metadata.yaml
- chains/suavetoliman/metadata.yaml
- chains/superpositiontestnet/metadata.yaml
- test/unit/chains.test.ts
chore: add deployer name for AW testnets
did a pass on all chains, seems only recent testnets were affected
> chore: add deployer name for AW testnets

- .changeset/honest-points-smoke.md
- chains/metadata.yaml
- chains/rootstock/metadata.yaml
- chains/rootstocktestnet/metadata.yaml
fix: remove gasLimit overrides for rootstock/rootstocktestnet
hardcoding the gaslimit this high causes problems in the relayer, as it will want the IGP payment to cover this limit. if the gas limit is set to the block gas limit, this is likely never going to happen. so we remove the overrides.
note, the overrides have been removed in the recently deployed agent configs. this is to update the default registry metadata to match our deployed agent setup.
y
manual
> fix: remove gasLimit overrides for rootstock/rootstocktestnet

- .changeset/neat-adults-march.md
- deployments/warp_routes/TIA/eclipse-stride-config.yaml
- deployments/warp_routes/stTIA/eclipse-stride-config.yaml
- The TIA token itself must be present if it's used as the IGP token
- Tested locally
> Add TIA token to new Stride deploys to work in warp UI

- .changeset/sweet-trees-perform.md
- deployments/warp_routes/SOL/eclipsemainnet-solanamainnet-config.yaml
Made a small mistake - probably should add a CI check for stuff like this
> fix: specify coinGeckoId for Solana warp route under the collateral token

- .changeset/ninety-lizards-lay.md
- deployments/warp_routes/CBBTC/base-zeronetwork-config.yaml
- deployments/warp_routes/CBBTC/ethereum-flowmainnet-config.yaml
- deployments/warp_routes/ETH/arbitrum-base-blast-bsc-ethereum-gnosis-lisk-mantle-mode-optimism-polygon-scroll-zeronetwork-zoramainnet-config.yaml
- deployments/warp_routes/POL/polygon-zeronetwork-config.yaml
- deployments/warp_routes/USDB/blast-zeronetwork-config.yaml
- deployments/warp_routes/USDC/arbitrum-base-endurance-config.yaml
- deployments/warp_routes/USDC/arbitrum-base-ethereum-lisk-optimism-polygon-zeronetwork-config.yaml
- deployments/warp_routes/WBTC/ethereum-mode-scroll-zeronetwork-config.yaml
- Adds coinGeckoId to recent warp routes, incl zeronetwork warp routes. Used for warp monitor purposes
- Sets the endurance USDC to a EvmHypCollateralFiat instead of EvmHypCollateral
> feat: add coinGeckoId to a bunch of new warp routes

- .changeset/stupid-avocados-give.md
- deployments/warp_routes/DAI/arbitrum-bsc-linea-polygon-addresses.yaml
- deployments/warp_routes/DAI/arbitrum-bsc-linea-polygon-config.yaml
Added LINEA mainnet route for DAI, accessible from Arbitrum, BSC, Polygon
New routes for DAI: 
1) Arbitrum - Linea
2) BSC - Linea
3) Polygon - Linea
Yes
All routes Linea - Arbitrum/BSC/Polygon successfully tested here https://hyperlane.superbridge.app/?hyperlaneWarpRoutes=172c7756-8e8c-4672-814b-9c01d9b48cd6
> Add LINEA mainnet route for DAI

- .github/workflows/combine.yml
- .github/workflows/optimize-svg.yml
When both combine or optimize-svg have changes, whoever finishes last would not be able to push because the other one already commited changes. I removed [skip ci] because it is not necessary and the initial thought was that it would loop but that should not be the case. Once one of the workflow updates it will trigger another check and if the other workflow has changes it will check again and do the proper changes.
Yes
Manual
> fix: remove skip ci from workflow

- .changeset/gorgeous-rivers-shake.md
- deployments/warp_routes/USDT/ethereum-superseed-addresses.yaml
- deployments/warp_routes/USDT/ethereum-superseed-config.yaml
Adds the USDT warp route artifacts for connecting ethereum and superseed
- YES
- CLI
- Ran UI locally
> feat(warp-route): added the USDT warp route from ethereum to superseed

- .changeset/early-olives-appear.md
- deployments/warp_routes/rstETH/ethereum-zircuit-addresses.yaml
- deployments/warp_routes/rstETH/ethereum-zircuit-config.yaml
Adds the rstETH warp route artifacts to connect ethereum and zircuit
Yes
CLI
> feat: add rstETH warp route from ethereum to zircuit

- .changeset/popular-ducks-thank.md
- deployments/warp_routes/PNDR/bsc-ethereum-lumiaprism-config.yaml
Add PNDR/bsc-ethereum-lumiaprism logoURI field
Yes
Local Warp UI
> feat: add pndr bsc-ethereum-lumiaprism logo

- .changeset/kind-shrimps-begin.md
- deployments/warp_routes/USDC/ethereum-form-config.yaml
- deployments/warp_routes/USDT/ethereum-form-config.yaml
add missing coingecko id to usdc and usdc routes on form
- YES
- Manual
- CLI
> fix: add missing coigecko id to form usdt and usdc routes

- scripts/validate-file-data.js
fixes #496 
Now validates that the path in logoURI for warp deployments actually exists, if it doesn't it will throw an error in the CI
Yes
Manual
> chore: validate logoURI path

- .changeset/dry-ears-agree.md
- deployments/warp_routes/TONY/base-solanamainnet-addresses.yaml
- deployments/warp_routes/TONY/base-solanamainnet-config.yaml
- A UI here https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/393 is available for anyone remaining who needs to unwind
> feat: replace old TONY/base-solanamainnet deploy with a new one

- .changeset/itchy-paws-tan.md
- src/utils.ts
This fixes the error that has been hard to debug:
```
Error: Error: Unresolved alias (the anchor must be set before the alias): a1
at Alias.toString (/Users/leyu/Desktop/Code/hyperlane/hyperlane-monorepo/node_modules/yaml/dist/nodes/Alias.js:72:23)
at Object.stringify (/Users/leyu/Desktop/Code/hyperlane/hyperlane-monorepo/node_modules/yaml/dist/stringify/stringify.js:93:25)
at Object.stringifyPair (/Users/leyu/Desktop/Code/hyperlane/hyperlane-monorepo/node_modules/yaml/dist/stringify/stringifyPair.js:97:32)
at Pair.toString (/Users/leyu/Desktop/Code/hyperlane/hyperlane-monorepo/node_modules/yaml/dist/nodes/Pair.js:33:29)
at Object.stringify (/Users/leyu/Desktop/Code/hyperlane/hyperlane-monorepo/node_modules/yaml/dist/stringify/stringify.js:90:21)
at stringifyBlockCollection …
```
> fix: Update toYamlString to not use aliasDuplicateObjects

- .changeset/nervous-elephants-flash.md
- chains/abstract/metadata.yaml
- chains/metadata.yaml
- chains/treasure/metadata.yaml
- chains/zklink/metadata.yaml
- chains/zksync/metadata.yaml
feat: set gnosisSafeTransactionServiceUrl for zksync-stack mainnets
found api urls by looking at per-chain metadata returned by each UI:
- zksync https://app.safe.global/home
- treasure https://app.palmeradao.xyz/welcome
- zklink https://safe.zklink.io/welcome
- abstract https://abstract-safe.protofire.io/welcome
> feat: set gnosisSafeTransactionServiceUrl for zksync-stack mainnets

- .changeset/grumpy-maps-tan.md
- deployments/warp_routes/SMOL/arbitrum-ethereum-treasure-addresses.yaml
- deployments/warp_routes/SMOL/arbitrum-ethereum-treasure-config.yaml
- deployments/warp_routes/SMOL/metadata.json
- Adds the existing SMOL token deployed by the treasure team
- Adds a metadata.json in preparation for a Solana token deploy. There is no image yet as the design is still being finalized, this will be updated later.
> feat: add SMOL config and metadata.json

- .changeset/spotty-points-tell.md
- deployments/warp_routes/SMOL/arbitrum-ethereum-solanamainnet-treasure-addresses.yaml
- deployments/warp_routes/SMOL/arbitrum-ethereum-solanamainnet-treasure-config.yaml
- Adds `solanamainnet` to the SMOL warp route
- Only connects solana to ethereum and treasure (not arbitrum) at the request of the team
> feat: add Solana to SMOL warp route

- .changeset/tame-jeans-decide.md
- deployments/warp_routes/LOGX/arbitrum-solanamainnet-addresses.yaml
- deployments/warp_routes/SMOL/arbitrum-ethereum-solanamainnet-treasure-addresses.yaml
- deployments/warp_routes/SOL/solanamainnet-sonicsvm-addresses.yaml
- deployments/warp_routes/SONIC/solanamainnet-sonicsvm-addresses.yaml
- deployments/warp_routes/USDC/solanamainnet-sonicsvm-addresses.yaml
- deployments/warp_routes/USDStar/solanamainnet-sonicsvm-addresses.yaml
- deployments/warp_routes/USDT/solanamainnet-sonicsvm-addresses.yaml
- deployments/warp_routes/sSOL/solanamainnet-sonicsvm-addresses.yaml
chore: remove remaining -addresses.yaml files
> chore: remove remaining -addresses.yaml files

- .changeset/witty-pumas-appear.md
- chains/metadata.yaml
- chains/unichain/metadata.yaml
- chains/worldchain/metadata.yaml
chore: update unichain and worldchain explorers
api keys have also been added in secrets
> chore: update unichain and worldchain explorers

- .changeset/quiet-adults-greet.md
- chains/ethereum/metadata.yaml
- chains/metadata.yaml
chore: add drpc endpoint to default ethereum RPC set
> chore: add drpc endpoint to default ethereum RPC set

- .changeset/modern-carpets-wink.md
- deployments/warp_routes/CDX/base-solanamainnet-config.yaml
- deployments/warp_routes/CDX/base-solanamainnet-deploy.yaml
- Deploys CDX/base-solanamainnet
- tested in local UI already
- ownership transfer already occurred
- no Coingecko ID yet
> feat: deploy CDX/base-solanamainnet

- .changeset/late-suits-eat.md
- deployments/warp_routes/SOL/hyperevm-solanamainnet-config.yaml
- deployments/warp_routes/SOL/hyperevm-solanamainnet-deploy.yaml
- Tested in UI
- Ownership has been transferred
- Settled on 9 decimals for the hyperevm side as this is what the e.g. wSOL https://etherscan.io/token/0xd31a59c85ae9d8edefec411d448f90841571b89c token does
> feat: Add SOL/hyperevm-solanamainnet

- scripts/check-mailbox-hooks.sh
Fixed an incorrect variable check in the script. Previously, the condition was checking `merkle_tree_hook` instead of `fallback_routing_hook`. Now, it correctly verifies `fallbackRoutingHook` before proceeding, ensuring the intended logic is applied.  
No breaking changes. The fix only corrects the variable being checked, preserving existing behavior while ensuring proper validation.  
Manually tested by running the script on various `addresses.yaml` files, confirming that `fallbackRoutingHook` is correctly validated and the script behaves as expected.
> chore: fix incorrect variable check for fallbackRoutingHook

- .changeset/eighty-drinks-smoke.md
- deployments/warp_routes/sSOL/solanamainnet-sonicsvm-config.yaml
- Was flagged that the `sSOL/solanamainnet-sonicsvm` `collateralAddressOrDenom` was inaccurate, fixes it
- Ideally we should have this be implied or unit tested but considering this out of the scope for now
- Went through all the other tokens and made sure they're good
> fix: correct sSOL/solanamainnet-sonicsvm collateralAddressOrDenom

- .changeset/tidy-parrots-promise.md
- deployments/warp_routes/ETH/base-ethereum-lumiaprism-config.yaml
Add `ETH/base-ethereum-lumiaprism` warp route deployment
Yes
CLI
> feat: ETH/base-ethereum-lumiaprism Warp Route Deployment

- .changeset/rare-impalas-thank.md
- deployments/warp_routes/ETH/base-ethereum-lumiaprism-deploy.yaml
Deploy config for ETH/base-ethereum-lumiaprism deploy config
Yes
> fix: add missing ETH/base-ethereum-lumiaprism deploy config

- .changeset/thirty-roses-play.md
- deployments/warp_routes/enzoBTC/bsc-hyperevm-deploy.yaml
- deployments/warp_routes/stBTC/bsc-hyperevm-deploy.yaml
Default ISM/empty addresses are not needed anymore for deploy config, removed from lorenzo warp routes
Yes
> chore: remove lorenzo routes default ISM

- .changeset/ninety-tomatoes-occur.md
- chains/schema.json
- deployments/warp_routes/schema.json
- package.json
- yarn.lock
feat: update SDK for starknet ProtocolType support
- latest SDK release includes the MVP starknet protocoltype support https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5677
This PR is a pre-requisite for merging the following:
- https://github.com/hyperlane-xyz/hyperlane-registry/pull/637
- https://github.com/hyperlane-xyz/hyperlane-registry/pull/661
> feat: update SDK for starknet ProtocolType support

- .changeset/clean-ladybugs-allow.md
- src/registry/registry-utils.ts
Adds optional `authToken` parameter to `getRegistry` function to support GitHub authentication for private repositories and rate limit handling.
- Added `authToken` parameter to `getRegistry`
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5501
> feat: add authToken parameter to getRegistry function

- .changeset/slimy-moose-lick.md
- deployments/warp_routes/ECLIP/arbitrum-neutron-deploy.yaml
- deployments/warp_routes/ETH/ethereum-viction-deploy.yaml
- deployments/warp_routes/TIA/arbitrum-neutron-deploy.yaml
- deployments/warp_routes/TIA/mantapacific-neutron-deploy.yaml
- deployments/warp_routes/TRUMP/arbitrum-avalanche-base-flowmainnet-form-optimism-solanamainnet-worldchain-deploy.yaml
- deployments/warp_routes/TRUMP/solanamainnet-trumpchain-deploy.yaml
- deployments/warp_routes/USDC/ethereum-viction-deploy.yaml
- deployments/warp_routes/USDT/ethereum-viction-deploy.yaml
Remove totalSupply from token metadata in warp deployments. The field seems to not be needed in most cases and could cause misconfiguration issues, on the synthetic token contract `totalSupply` was used, which mints tokens to the message sender. 
Instead we now apply a `initialSupply` directly to the synthetic token without the need to use `totalSupply`
Related [PR](https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5686) from the monorepo
Yes
> chore: remove total supply from deployments config

- .changeset/popular-bottles-develop.md
- deployments/warp_routes/USDT/base-celo-fraxtal-ink-lisk-mode-optimism-soneium-superseed-unichain-worldchain-config.yaml
- package.json
- yarn.lock
1. Update hyperlane sdk package
2. Update oUSDT warp route token standards from:
- `XERC20` -> `VSXERC20`
- `XERC20Lockbox` -> `VSXERC20Lockbox`
3. Remove connections to `ink`
Yes
Local UI
> chore: change oUSDT token standard

- .changeset/nasty-sloths-train.md
- deployments/warp_routes/USDT/base-celo-fraxtal-ink-lisk-mode-optimism-soneium-superseed-unichain-worldchain-config.yaml
- test/unit/registry.test.ts
Remove connections from worldchain in oUSDT warp deployments
Yes
Local UI
> chore: remove worldchain connection in oUSDT

- .changeset/healthy-cows-argue.md
- deployments/warp_routes/USDCSTAGE/arbitrum-base-ethereum-ink-optimism-solanamainnet-superseed-config.yaml
Rename superseed staging warp route's symbol from USDC to USDCSTAGE
Yes
> chore: rename usdc route to usdcstage

- .changeset/kind-balloons-matter.md
- chains/schema.json
- package.json
- yarn.lock
Update to Hyperlane SDK 11.0.0, which includes support for the new "cosmosnative" ProtocolType.
Will update the relevant metadata in a separate PR.
> feat: update to latest major hyperlane SDK

- .github/workflows/update-nitro-chains.yml
We're currently spending a lot of time laboriously checking if a chain is a nitro chain in main before doing the metadata/addresses update. This PR splits the check to a separate job so that the actual built-out metadata/addresses files can be updated quicker.
yes
ci
> chore(ci): split nitro check+update to a separate job

- .changeset/three-balloons-remain.md
- chains/ethereum/metadata.yaml
- chains/metadata.yaml
fix: rotate default ethereum RPCs
since ankr endpoint is severely rate limiting in CI
> fix: rotate default ethereum RPCs

- .changeset/dirty-masks-pretend.md
- src/registry/GithubRegistry.ts
Fixes a CORS error that occurs when the GithubRegistry makes requests to raw.githubusercontent.com. The issue was introduced when the X-GitHub-Api-Version header was added to all requests in the @hyperlane-xyz/hyperlane-registry package. While this header is required for GitHub API calls, it causes CORS preflight failures when making requests to raw.githubusercontent.com for metadata and addresses.
This fix:
- Removes the X-GitHub-Api-Version header specifically for raw.githubusercontent.com requests
- Maintains the header for actual GitHub API calls
- Resolves browser-environment CORS errors when fetching metadata and addresses
Yes - This change is fully backward compatible. It only modifies the HTTP request header handling without changing any functional behavior or data structures.
All …
> fix: update fetch method to use GITHUB_API_URL for auth token usage

- .changeset/dry-buttons-unite.md
- deployments/warp_routes/CBBTC/base-ethereum-superseed-config.yaml
This PR removes routing between base and ethereum for superseed cbbtc
Yes
Local testing with `yarn link` on warp ui
> feat: Remove routing between base and ethereum for superseed cbbtc

- .changeset/moody-mugs-whisper.md
- chains/polygon/metadata.yaml
fix: update default polygon RPCs
> fix: update default polygon RPCs

- .changeset/tidy-donuts-train.md
- deployments/warp_routes/SMOL/arbitrum-ethereum-solanamainnet-treasure-deploy.yaml
- deployments/warp_routes/USDC/arbitrum-base-ethereum-lisk-optimism-polygon-zeronetwork-deploy.yaml
- deployments/warp_routes/USDT/arbitrum-ethereum-mantle-mode-polygon-scroll-zeronetwork-deploy.yaml
This PR Updates remoteRouter names to domainIds. Related https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/6066
Yes
yarn check-warp-deploy
> chore: Update remoteRouter names to domainIds

- .changeset/curvy-maps-care.md
- deployments/warp_routes/USDTSTAGING/base-bitlayer-celo-ethereum-fraxtal-ink-linea-lisk-mantle-metal-metis-mode-optimism-ronin-soneium-sonic-superseed-unichain-worldchain-config.yaml
Change oUSDT symbol to oUSDTSTAGE and fixed issue with build
Yes
> fix: oUSDT staging symbol

- .changeset/violet-ads-burn.md
- deployments/warp_routes/USDT/base-bitlayer-celo-ethereum-fraxtal-ink-linea-lisk-mantle-metal-metis-mode-optimism-ronin-soneium-sonic-superseed-unichain-worldchain-config.yaml
Remove connections for:
- sonic
- bitlayer
- ronin
- mantle
- linea
Yes
> chore: update oUSDT route connections

- .changeset/rotten-windows-drop.md
- deployments/warp_routes/USDT/base-bitlayer-celo-ethereum-fraxtal-ink-linea-lisk-mantle-metal-metis-mode-optimism-ronin-soneium-sonic-superseed-unichain-worldchain-config.yaml
Remove connection to ink from oUSDT route
Yes
> chore: remove ink connection for oUSDT

- .changeset/tidy-chairs-pump.md
- chains/eclipsemainnet/metadata.yaml
Update eclipse block explorer URL 
Yes
> chore: update eclipsemainnet block explorer

- .changeset/cuddly-experts-jump.md
- chains/plume/metadata.yaml
- chains/plumetestnet2/metadata.yaml
chore: update plumenetwork.xyz to plume.org
> chore: update plumenetwork.xyz to plume.org

- .changeset/cuddly-sheep-kneel.md
- src/registry/GithubRegistry.ts
This PR fixes the zip-downloading issue experienced by browser-based registry clients. We tried to download the zip archives in a way that's prevented by CORS. There's no quick workaround, so the code now reverts to old behaviour when running in a browser.
Yes
- No new unit-tests added
- Manually tested from hyperlane-explorer
> fix: only download zip archives when in Node.js

- .changeset/cyan-phones-greet.md
- src/fs/FileSystemRegistry.ts
This pull request updates the `FileSystemRegistry` to not throw when adding a warp route configuration. This essentially removes the need for an update function.
Yes
- tested through `yarn tsx ./scripts/warp-routes/export-warp-configs.ts -e mainnet3`
> Remove file exists, then throw logic for addWarpRoute

- .changeset/cyan-flies-lie.md
- deployments/warp_routes/ETH/arbitrum-base-blast-bsc-ethereum-gnosis-lisk-mantle-mode-optimism-polygon-scroll-zeronetwork-zoramainnet-config.yaml
- deployments/warp_routes/ETH/arbitrum-bsc-kalychain-polygon-config.yaml
Add logoURI to missing ETH warp routes
Yes
> chore: add logoURI to missing routes

- .changeset/strange-dots-grin.md
- deployments/warp_routes/TGT/bsc-immutablezkevmmainnet-config.yaml
This pull request includes a minor update to the `bsc-immutablezkevmmainnet-config.yaml` file for the TGT token configuration. The change adds a `coinGeckoId` field to specify the token's identifier on CoinGecko.
> chore: Add TGT coingecko

- .changeset/odd-cameras-unite.md
- deployments/warp_routes/warpRouteConfigs.yaml
- scripts/build.ts
This pull request updates the `scripts/build.ts` to use `warpRouteId` instead of deriving the ID based on token symbols for backwards compatibility
Yes, but need to update warp UI to update `TIA.n` routes
With warp UI
> chore: Update build.ts to generate warpRouteConfigs.yaml

- .changeset/olive-cameras-laugh.md
- chains/starknet/metadata.yaml
- Currently, we are using ETH to pay the gas.
> feat(chain): switch starknet's coingeckoId from `starknet` to `ethereum`

- scripts/check-warp-deploy.sh
chore: don't check deleted routes
- currently the diffing just looks at anything that changed, so if a file was deleted then we would try to check-warp-deploy that. but it does not exist. e.g 
- by adding `--diff-filter=ARM`, we're only considering additions/renames/modifications
- tested by remaking the ousdt PR but with this change cherry-picked: https://github.com/hyperlane-xyz/hyperlane-registry/pull/928
- correctly didn't include removed routes:
- correctly [reported](https://github.com/hyperlane-xyz/hyperlane-registry/pull/928#issuecomment-2934887322) staging ✅ and prod ❌:
> chore: don't check deleted routes

- .changeset/tricky-windows-design.md
- package.json
- yarn.lock
chore: update to hyperlane sdk 13.2.1
- https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/6422
> chore: update to hyperlane sdk 13.2.1

- .changeset/little-years-knock.md
- deployments/warp_routes/oXAUT/production-config.yaml
Since it used the underlying, it used the original name. This PR updates it to match the other chains
> chore: Update oxaut core name and symbol for lockbox

- .changeset/brave-cobras-remember.md
- deployments/warp_routes/USDC/mainnet-cctp-config.yaml
- deployments/warp_routes/USDC/testnet-cctp-config.yaml
- deployments/warp_routes/warpRouteConfigs.yaml
Add collateralAddressOrDenom and logo to `USDC/mainnet-cctp` and `USDC/testnet-cctp`
Yes
> chore: add collateralAddressOrDenom and logoURI to USDC cctp configs

- .changeset/odd-needles-drive.md
- deployments/warp_routes/TIA/basesepolia-celestiatestnet-config.yaml
- deployments/warp_routes/TIA/basesepolia-celestiatestnet-deploy.yaml
> chore: add `TIA` testnet

- .changeset/dirty-jobs-sleep.md
- deployments/warp_routes/oXAUT/production-deploy.yaml
This PR adds the ownerOverride.collateralToken such that it transfers over the underlying xerc20 owners using check-warp-deploy
Yes
> chore: Update oXAUT's xerc20 owners

- .changeset/heavy-pumpkins-rhyme.md
- chains/celo/metadata.yaml
applying metadata changes now that celo has stabilised as an L2
- update reorg period 
- update technical stack
- update block time
> chore: update celo chain metadata

- .changeset/rude-beans-swim.md
- deployments/warp_routes/oUSDT/production-config.yaml
Enable oUSDT on UI for bitlayer, mantle, ronin, sonic.
> chore: enable new chains on ousdt UI

- .changeset/brave-rivers-camp.md
- chains/lumia/metadata.yaml
chore: deprecate legacy lumia mailbox
> chore: deprecate legacy lumia mailbox

- .changeset/orange-hornets-hide.md
- deployments/warp_routes/TIA/arbitrum-celestia-neutron-config.yaml
- deployments/warp_routes/warpRouteConfigs.yaml
Remove neutron connection for TIA/arbitrum-celestia-neutron route
Yes
UI testing
> chore: remove neutron connection TIA/arbitrum-celestia-neutron

- .changeset/cuddly-onions-hope.md
- deployments/warp_routes/USDC/electroneum-config.yaml
- deployments/warp_routes/USDC/electroneum-deploy.yaml
This PR moves the logorUrl and coinGeckoId to the correct config for electroneum USDC
Yes
> chore: Add logourl and coinGeckoId to the correct config
