hyperlane-xyz/hyperlane-registry

.changeset/fast-kings-sip.md
README.md
package.json

Mostly to test the changesets integration

Update readme and version

---

.changeset/witty-boats-end.md
chains/schema.json
deployments/warp_routes/schema.json
package.json
test/health/explorer-health.test.ts
yarn.lock

Update to Hyperlane SDK 3.1.1 and fix tests accordingly
Yes
Locally

Update to Hyperlane SDK 3.1.1

---

.changeset/gold-hairs-jam.md
src/registry/BaseRegistry.ts
src/registry/GithubRegistry.ts
src/registry/IRegistry.ts
src/registry/LocalRegistry.ts
test/unit/registry.test.ts

- Add `getChainLogoUri` method to IRegistry
- Improve caching of single-chain data queries
- Avoid errors on missing chain files
Yes
Tested in widget lib manually

Additions to serve Hyperlane Explorer

---

.github/workflows/ci.yml

- support for merge queues into `main`

ci: support for merge queues into `main`

---

.changeset/metal-phones-notice.md
chains/blast/metadata.yaml
chains/mode/metadata.yaml

chore: add blast/mode safe tx url

chore: add blast/mode safe tx url

---

.changeset/perfect-geese-float.md
src/registry/GithubRegistry.ts
test/unit/registry.test.ts

- Fix unstable order of github file fetch results
- Add more unit test coverage of MergedRegistry

Fix bug with GithubRegistry file fetching

---

.changeset/fresh-walls-compete.md
chains/mantle/metadata.yaml

moving mantle confirmations from tx overrides to registry: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4051#discussion_r1662781625

chore: update mantle confirmations required

---

.changeset/config.json
.github/workflows/ci.yml

Add CI check for existence of changeset 
Yes
In CI

Add CI for changeset check

---

.github/workflows/ci.yml

fix: auto-pass changeset step in merge queue

fix: auto-pass changeset step in merge queue

---

.github/workflows/ci.yml

Attempted fix for failure: https://github.com/hyperlane-xyz/hyperlane-registry/actions/runs/10187397323/job/28181348399

Define GH_TOKEN env for changeset ci job

---

.changeset/sharp-bears-remember.md
deployments/warp_routes/SOL/eclipse/metadata.json

feat: Eclipse SOL token metadata

---

.changeset/eight-camels-explain.md
chains/ethereum/metadata.yaml
chains/metadata.yaml

Only impacts CLI consumers to reasonable wait for inclusion

Reduce Ethereum confirmations wait

---

.changeset/odd-rivers-matter.md
chains/cheesechain/metadata.yaml
deployments/warp_routes/USDC/cheesechain-ethereum-addresses.yaml
deployments/warp_routes/USDC/cheesechain-ethereum-config.yaml

- Added CheeseChain
- Added USDC collateral vault powered by https://app.morpho.org/vault?vault=0xdd0f28e19C1780eb6396170735D45153D261490d&network=mainnet
- Example Deposit: https://etherscan.io/tx/0xe74758fcb89113460c39d80c1f9a9c87f8070ce6d00fe3f67cb9293fb63c358e

feat: deploy to cheesechain and add USDC Collateral Vault

---

.changeset/good-squids-double.md
chains/metadata.yaml
chains/polygon/metadata.yaml
chains/polygonamoy/metadata.yaml

feat: change MATIC to POL

---

chains/heneztestnet/metadata.yaml

fix: heneztestnet lint

---

.changeset/eighty-pears-impress.md
chains/metadata.yaml
chains/scroll/metadata.yaml

feat: update scroll reorg period

---

.changeset/cold-months-heal.md
chains/addresses.yaml
chains/eclipsemainnet/metadata.yaml
chains/metadata.yaml

chore: add eclipsemainnet block explorer
- drive-by yarn build

chore: add eclipsemainnet block explorer

---

.changeset/wise-files-breathe.md
chains/everclear/metadata.yaml
chains/metadata.yaml

fix: update everclear explorer urls

fix: update everclear explorer urls

---

deployments/warp_routes/tETH/metadata.json

chore: update tETH image in metadata.json

---

.changeset/sweet-trees-marry.md
chains/metadata.yaml
chains/solanamainnet/metadata.yaml

chore: update solana explorer to solscan
- for more readable transactions

chore: update solana explorer to solscan

---

.changeset/popular-geckos-suffer.md
chains/alephzero/metadata.yaml
chains/metadata.yaml

requested by Aleph Zero contributors to avoid confusion with original Aleph Zero L1

changed `displayName` to Aleph Zero EVM

---

.changeset/lucky-turkeys-cheer.md
chains/alfajores/metadata.yaml
chains/arbitrumsepolia/metadata.yaml
chains/basesepolia/metadata.yaml
chains/bsctestnet/metadata.yaml
chains/connextsepolia/metadata.yaml
chains/eclipsetestnet/metadata.yaml
chains/ecotestnet/metadata.yaml
chains/fuji/metadata.yaml
chains/holesky/metadata.yaml
chains/metadata.yaml
chains/plumetestnet/metadata.yaml
chains/polygonamoy/metadata.yaml
chains/scrollsepolia/metadata.yaml
chains/sepolia/metadata.yaml
chains/solanatestnet/metadata.yaml
chains/superpositiontestnet/metadata.yaml

chore: add gasCurrencyCoinGeckoId for core testnets

chore: add gasCurrencyCoinGeckoId for core testnets

---

.changeset/few-eels-tickle.md
chains/chiliz/metadata.yaml
chains/metadata.yaml

Update chiliz RPCs
y
`cast gas-price --rpc-url`, the removed RPC returned different values to all other RPCs tested

fix: update chiliz RPCs

---

.changeset/loud-items-hunt.md
chains/chiliz/metadata.yaml
chains/metadata.yaml

chore: add maxPriorityFeePerGas for chiliz
yes
yes - works and currently in prod relayer

chore: add maxPriorityFeePerGas for chiliz

---

.changeset/few-olives-join.md
deployments/warp_routes/EZETH/arbitrum-base-blast-bsc-ethereum-fraxtal-linea-mode-optimism-sei-taiko-zircuit-config.yaml

Rename ezEth name to redEth for Sei

fix: update ezEth name to redEth

---

.changeset/gorgeous-readers-decide.md
src/index.ts

Export createWarpRouteConfigId function
Yes

feat(warpUtils): Export createWarpRouteConfigId function

---

.changeset/gorgeous-plums-watch.md
deployments/warp_routes/TIA/metadata.json
deployments/warp_routes/stTIA/metadata.json

feat: TIA and stTIA token metadata

---

.changeset/calm-tools-build.md
chains/chiliz/metadata.yaml
chains/metadata.yaml

fix: revert chiliz reorg period
yes
relayer sad times - [context](https://discord.com/channels/935678348330434570/1298963431743029359/1298965808327954442)

fix: revert chiliz reorg period

---

.changeset/few-zoos-crash.md

fix: make cheesechain change minor

fix: make cheesechain change minor

---

.changeset/odd-dodos-drop.md
deployments/warp_routes/ORCA/eclipsemainnet-solanamainnet-addresses.yaml
deployments/warp_routes/ORCA/eclipsemainnet-solanamainnet-config.yaml
deployments/warp_routes/USDT/eclipsemainnet-ethereum-addresses.yaml
deployments/warp_routes/USDT/eclipsemainnet-ethereum-config.yaml
deployments/warp_routes/WBTC/eclipsemainnet-ethereum-addresses.yaml
deployments/warp_routes/WBTC/eclipsemainnet-ethereum-config.yaml

Artifacts for ORCA, WBTC, USDT

feat: Eclipse routes #2 artifacts

---

.changeset/modern-ducks-shake.md
chains/metadata.yaml
chains/moonbase/metadata.yaml
test/unit/chains.test.ts

add test to ensure chains have domainId set
effectively a metadata change without a schema update so shouldn't break back compat as the schema is unchanged
ci passes

feat: ensure domainIds are required

---

.changeset/new-ravens-happen.md
chains/metadata.yaml

fix: rebuild metadata.yaml
yarn build

fix: rebuild metadata.yaml

---

.changeset/nervous-readers-smoke.md
chains/ink/metadata.yaml
chains/metadata.yaml
chains/scroll/metadata.yaml

feat: update RPCs for ink and scroll

feat: update RPCs for ink and scroll

---

.changeset/short-windows-camp.md
chains/injective/metadata.yaml

Update Injective RPC URL
Yes
Manual

chore: update injective rpc URL

---

.changeset/four-trees-taste.md
deployments/warp_routes/USDC/ethereum-ink-addresses.yaml
deployments/warp_routes/USDC/ethereum-ink-config.yaml

Add ethereum-ink USDC artifacts

feat: Add ethereum-ink USDC artifacts

---

.changeset/sour-rules-hammer.md
chains/soneium/metadata.yaml

fix: update soneium explorer URL

fix: update soneium explorer URL

---

.changeset/sweet-rabbits-joke.md
deployments/warp_routes/CBBTC/ethereum-superseed-addresses.yaml
deployments/warp_routes/CBBTC/ethereum-superseed-config.yaml
deployments/warp_routes/USDC/ethereum-superseed-addresses.yaml
deployments/warp_routes/USDC/ethereum-superseed-config.yaml

Add SuperSeed FiatToken warp route 
Yes
With CLI

Add SuperSeed FiatToken warp route 

---

.changeset/wise-bears-leave.md
deployments/warp_routes/TONY/base-solanamainnet-addresses.yaml
deployments/warp_routes/TONY/base-solanamainnet-config.yaml

- From deploying the warp route.
- We should consider what to do with tokens without coingecko prices in the future - not super satisfactory with the current placeholder of bonk

feat: add TONY deploy artifacts

---

.changeset/cyan-walls-dream.md
deployments/warp_routes/CBBTC/base-zeronetwork-deploy.yaml
deployments/warp_routes/CBBTC/ethereum-superseed-deploy.yaml
deployments/warp_routes/LUMIA/bsc-ethereum-lumia-deploy.yaml
deployments/warp_routes/TONY/base-solanamainnet-deploy.yaml
deployments/warp_routes/TRUMP/arbitrum-avalanche-base-flowmainnet-form-optimism-solanamainnet-worldchain-deploy.yaml
deployments/warp_routes/USDC/arbitrum-base-ethereum-lisk-optimism-polygon-zeronetwork-deploy.yaml
deployments/warp_routes/USDC/ethereum-superseed-deploy.yaml
deployments/warp_routes/USDT/arbitrum-ethereum-mantle-mode-polygon-scroll-zeronetwork-deploy.yaml

Updates some existing configs
Yes

fix: warp config updates existing

---

.changeset/little-pants-relate.md
deployments/warp_routes/CBBTC/base-zeronetwork-deploy.yaml
deployments/warp_routes/ETH/ethereum-viction-deploy.yaml
deployments/warp_routes/TRUMP/solanamainnet-trumpchain-deploy.yaml
deployments/warp_routes/pumpBTCsei/ethereum-sei-deploy.yaml

This PR updates several config by remove unused properties. Mostly, if there is a proxyAdmin object already defined, then remove the overrides.
Each config has been verified with the Checker.
Yes

chore: clean up warp config part 1

---

.changeset/short-parents-wink.md
deployments/warp_routes/ART/artela-base-solanamainnet-config.yaml

Updated `ART/artela-base-solanamainnet-config.yaml` coinGeckoId
Yes
Manual

chore: Update ART coinGeckoId

---

.changeset/spotty-files-hunt.md
deployments/warp_routes/EZETHSTAGE/arbitrum-base-berachain-blast-bsc-ethereum-fraxtal-linea-mode-optimism-sei-swell-taiko-unichain-zircuit-deploy.yaml

This Updates the EZETHSTAGE to use a safe
Yes

fix: Update EZETHstage unichain to use Safe

---

.changeset/tame-lizards-attack.md
CHANGELOG.md
package.json

Reverts hyperlane-xyz/hyperlane-registry#583

revert: 9.5.1

---

.changeset/smooth-socks-heal.md
chains/metadata.yaml
chains/sophon/metadata.yaml

feat: add gnosis safe API for sophon

feat: add gnosis safe API for sophon

---

.changeset/friendly-points-teach.md
chains/lisk/metadata.yaml
chains/soneium/metadata.yaml
chains/superseed/metadata.yaml
chains/unichain/metadata.yaml
chains/worldchain/metadata.yaml

- Add safe tx service urls for lisk, worldchain, superseed, soneium and unichain

chore(txService): Add safe tx service urls

---

.changeset/slimy-games-shop.md
deployments/warp_routes/pumpBTCuni/ethereum-unichain-config.yaml

feat(warp): Add logoURI to pumpBTCuni/ethereum-unichain deployment

---

.changeset/swift-singers-suffer.md

This PR updates the changeset description to reflect that it is PZETH

fix: Update PZETH changeset

---

.changeset/swift-singers-suffer.md

Reverts hyperlane-xyz/hyperlane-registry#639 going to include this in the pzeth branch

Revert "fix: Update PZETH changeset"

---

.changeset/calm-birds-admire.md

This PR Adds the changeset for #643

chore: Add changeset for #643

---

.changeset/sixty-dryers-visit.md
deployments/warp_routes/REZ/base-ethereum-config.yaml

This PR updates the REZ logo uri

chore: update rez logo

---

.changeset/red-garlics-swim.md
package.json
src/registry/registry-utils.ts
yarn.lock

- Add `branch` to getRegistry() to allow fetching the Registry of different branches
- Up the sdk version to latest to allow `yarn link`
Yes
Tested check-deploy using `yarn link`

feat: add branch to get registry

---

.changeset/polite-hornets-develop.md
deployments/warp_routes/USDT/base-celo-fraxtal-ink-lisk-mode-optimism-soneium-superseed-unichain-worldchain-config.yaml

- add ousdt coingecko id to support collateral value monitoring
- manual

chore: add ousdt coingecko id

---

.changeset/spicy-timers-prove.md
deployments/warp_routes/CDX/base-solanamainnet-sophon-config.yaml
deployments/warp_routes/ECLIP/arbitrum-neutron-config.yaml
deployments/warp_routes/FORM/ethereum-form-config.yaml
deployments/warp_routes/LUMIA/bsc-ethereum-lumiaprism-config.yaml
deployments/warp_routes/VANA/ethereum-vana-config.yaml

- add coingecko ids for multiple warp configs

chore: add coingecko ids for multiple warp configs

---

.changeset/thirty-knives-switch.md
deployments/warp_routes/USDC/arbitrum-base-ethereum-ink-optimism-solanamainnet-superseed-deploy.yaml

Update Superseed USDC configs with the team multisigs
Yes

chore: transfer ownership superseed USDC

---

.changeset/cyan-years-clean.md
chains/kyvetestnet/metadata.yaml

Reverts hyperlane-xyz/hyperlane-registry#728

Revert "feat: update kyvetestnet protocol type to `cosmosnative`"

---

.changeset/proud-turkeys-push.md
chains/schema.json
package.json
yarn.lock

chore: update hyperlane sdk

---

.changeset/wild-snails-count.md
chains/modetestnet/metadata.yaml

chore: update modetestnet deployer

chore: update modetestnet deployer

---

.changeset/rich-foxes-happen.md
deployments/warp_routes/ETH/ethereum-hyperevm-deploy.yaml
deployments/warp_routes/USDT/ethereum-hyperevm-deploy.yaml
deployments/warp_routes/WBTC/ethereum-hyperevm-deploy.yaml

This PR updates hyperevm configs to include proxyAdmin.
Need for:
- https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5864
Yes
Ran `yarn tsx check-warp-deploy.ts...`

fix: update hyperevm config to include proxyAdmin

---

.changeset/fifty-waves-watch.md
deployments/warp_routes/USDC/coti-ethereum-config.yaml
deployments/warp_routes/USDC/coti-ethereum-deploy.yaml

This PR adds USDC/coti-ethereum for COTI
Yes

feat: USDC/coti-ethereum

---

.changeset/yellow-ducks-cheat.md
chains/arbitrum/metadata.yaml
chains/base/metadata.yaml
chains/bsc/metadata.yaml
chains/ethereum/metadata.yaml
chains/metadata.yaml
chains/optimism/metadata.yaml
test/health/rpc-health.test.ts

Updates the RPC list for arbitrum, base, bsc, ethereum and optimism
- YES
-YES

fix(chains): updated rpcs for arb base bsc op and eth

---

.changeset/tidy-donkeys-hunt.md
deployments/warp_routes/USDC/coti-ethereum-config.yaml

This PR adds logoURI for Coti
Yes

chore: Add logoURI for Coti

---

.changeset/purple-cherries-hide.md
deployments/warp_routes/LUMIA/arbitrum-avalanche-base-bsc-ethereum-lumiaprism-optimism-polygon-config.yaml

This PR updates the config with the lumia logo
Yes

chore: update lumia logo

---

.changeset/metal-penguins-dance.md
deployments/warp_routes/USDT/arbitrum-ethereum-mantle-mode-polygon-scroll-zeronetwork-deploy.yaml

- Update zero network USDT owner to match onchain
- Remove extra ownerOverrides
Yes
Ran `yarn test:unit` to ensure matching. Also, ran infra checker

chore: Update usdt zero

---

.changeset/witty-humans-thank.md
chains/schema.json
deployments/warp_routes/schema.json
package.json
yarn.lock

chore: update to hyperlane sdk 12.3.0

chore: update to hyperlane sdk 12.3.0

---

.changeset/weak-berries-tan.md
chains/milkyway/metadata.yaml
deployments/warp_routes/MILK/bsc-milkyway-config.yaml

chore: set correct coingecko id for milkyway

---

.changeset/spicy-dancers-yawn.md
deployments/warp_routes/USDC/ancient8-ethereum-deploy.yaml
deployments/warp_routes/USDT/eclipsemainnet-ethereum-solanamainnet-deploy.yaml
deployments/warp_routes/WBTC/eclipsemainnet-ethereum-deploy.yaml

Generated through export-config
Related: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/6093
Yes

chore: Add proxyAdmin with explicit owners

---

.changeset/brave-hairs-yell.md
deployments/warp_routes/USDT/base-bitlayer-celo-ethereum-fraxtal-ink-linea-lisk-mantle-metal-metis-mode-optimism-ronin-soneium-sonic-superseed-unichain-worldchain-config.yaml

- Remove `worldchain` connection, 
- add `logoURI` to all chains
- add `coinGeckoId` to `celo` and `ethereum`
Yes

chore: Update oUSDT extension

---

chains/fluence/metadata.yaml

fix: update fluence index.from

---

.changeset/quick-kings-hammer.md
chains/arbitrum/metadata.yaml
chains/arbitrumsepolia/metadata.yaml
chains/avalanche/metadata.yaml
chains/base/metadata.yaml
chains/basesepolia/metadata.yaml
chains/bsc/metadata.yaml
chains/celo/metadata.yaml
chains/cronos/metadata.yaml
chains/ethereum/metadata.yaml
chains/fraxtal/metadata.yaml
chains/gnosis/metadata.yaml
chains/linea/metadata.yaml
chains/moonbeam/metadata.yaml
chains/opbnb/metadata.yaml
chains/optimism/metadata.yaml
chains/optimismsepolia/metadata.yaml
chains/polygon/metadata.yaml
chains/polygonzkevm/metadata.yaml
chains/scroll/metadata.yaml
chains/sei/metadata.yaml
chains/sepolia/metadata.yaml
chains/sonic/metadata.yaml
chains/sonicblaze/metadata.yaml
chains/taiko/metadata.yaml
chains/unichain/metadata.yaml
chains/worldchain/metadata.yaml

Add explorer API keys to some (most popular) chains
Yes

chore: Add explorer api keys

---

.changeset/few-moons-cough.md
deployments/warp_routes/wfragJTO/eclipsemainnet-solanamainnet-soon-config.yaml

This PR fixes the `wfragJTO` collateral address.
Yes
N/A

fix: `wfragJTO` collateral address

---

.changeset/slimy-eggs-run.md
deployments/warp_routes/MIRAI/abstract-bsc-solanamainnet-deploy.yaml
test/unit/registry.test.ts

Just an update
- YES
- CLI
- Infra checker

chore: updated mirai ownership config

---

.changeset/real-cows-buy.md
deployments/warp_routes/TGT/bsc-immutablezkevmmainnet-deploy.yaml

This PR updates to TGT warp route to Fireblocks owners
Yes/No

chore: Update to TGT warp route to Fireblocks owners

---

.changeset/lemon-wombats-clean.md
package.json
yarn.lock

chore: update hyperlane SDK to 13.0.0

chore: update hyperlane SDK to 13.0.0

---

.changeset/strange-cougars-pull.md
deployments/warp_routes/CHILL/metadata.json

This PR adds the metadata for `CHILL`.
Yes
N/A

chore: add `CHILL` metadata

---

.changeset/real-sloths-move.md
deployments/warp_routes/adraSOL/solanamainnet-sonicsvm-config.yaml

This PR adds `adraSOL` deploy config.
Yes
N/A

chore: add `adraSOL` deploy config

---

.changeset/fair-ladybugs-sing.md
chains/fluence/metadata.yaml

chore: update fluence coingecko id

chore: update fluence coingecko id

---

.changeset/wise-candles-explode.md
deployments/warp_routes/TRUMP/starknet-config.yaml
deployments/warp_routes/TRUMP/starknet-deploy.yaml

chore: add `TRUMP` starknet
Yes
N/A

chore: add `TRUMP` starknet

---

.changeset/rude-cars-own.md
chains/metadata.yaml

Updates arbitrum and optimism block times

chore: update block times

---

deployments/warp_routes/USDC/arbitrum-base-ethereum-ink-optimism-solanamainnet-superseed-config.yaml

Update connections for the USDC superseed route to connect all chains
Yes

chore: update USDC superseed connections

---

.changeset/chilly-weeks-exist.md
chains/botanix/metadata.yaml

chore: remove botanix transaction overrides

chore: remove botanix transaction overrides

---

.changeset/weak-drinks-hug.md
src/registry/HttpClientRegistry.ts

Adds getWarpDeployConfig to HttpClientRegistry
Yes
Manual

feat: Add getWarpDeployConfig route to HttpclientRegistry

---

.changeset/honest-houses-obey.md
deployments/warp_routes/EDGEN/bsc-edgenchain-ethereum-config.yaml

chore: add edgen coingecko-id

---

.changeset/twenty-scissors-pull.md
deployments/warp_routes/USDC/ancient8-ethereum-deploy.yaml

Sync ancient8 usdc route ownership config
- yes
- manual
-

chore: sync ancient8 usdc route config

---

.changeset/forty-steaks-exist.md
deployments/warp_routes/TGT/bsc-immutablezkevmmainnet-deploy.yaml

This Pr Updates TGT owners to fix alerts

chore: Update TGT owners

---

.changeset/curly-sheep-smile.md
deployments/warp_routes/USDT/matchain-config.yaml

This PR adds the logo to the USDT/matchain route

chore: add logo to USDT/matchain

---

.changeset/shaggy-dragons-shop.md
deployments/warp_routes/MITO/mitosis-config.yaml

chore: add mito gecko id

---

.changeset/late-candles-joke.md
deployments/warp_routes/oXAUT/production-deploy.yaml

Description
This PR updates oXAUT base owner to AW safe

chore: Update oXAUT base XERC20 owner to AW safes

---

.changeset/curvy-deers-roll.md
deployments/warp_routes/SOL/radix-config.yaml
deployments/warp_routes/SOL/radix-deploy.yaml

chore: add `SOL/radix` artifacts

chore: add `SOL/radix` artifacts
